### ISSUE TITLE
BioSimSpace on OS X cannot CI/CD because of failing SOMD

### ISSUE THREAD

**Issue by chryswoods** [michellab/BioSimSpace#55]
BioSimSpace cannot complete a CI/CD on OS X due to SOMD now failing in the latest version of sire-devel-osx. It seems that the merged pull request from @SofiaBariami has resulted in a SOMD executable that cannot complete the tests asked of it by BioSimSpace. I have raised this as an issue in Sire.

https://github.com/michellab/Sire/issues/245

If this will take a while to fix then we will need to roll Sire back to the pre-merged state so that BioSimSpace development can continue.

**Comment by lohedges** [comment]
When you're in, we can run the failing test locally on your laptop to see what the exact error message is.

**Comment by lohedges** [comment]
I made a minor update and now the latest Linux build isn't working either. I've downloaded the binary and get a segmentation fault as soon as I try to import BioSimSpace. Currently re-compiling Sire locally to see if the latest merges break my local install too.

**Comment by lohedges** [comment]
This is the `gdb` trace for the following test script.

```python
import BioSimSpace as BSS
```

```bash
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/lester/Downloads/BioSimSpace.app/bin/python...done.
(gdb) run test.py
Starting program: /home/lester/Downloads/BioSimSpace.app/bin/python test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff36dc700 (LWP 27620)]
[Detaching after fork from child process 27621]
[Detaching after fork from child process 27637]
[Thread 0x7ffff36dc700 (LWP 27620) exited]
[Detaching after fork from child process 27649]
[New Thread 0x7ffff36dc700 (LWP 27651)]
[New Thread 0x7fffe5d4f700 (LWP 27652)]
[New Thread 0x7fffe154e700 (LWP 27653)]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffe8d4a2e1 in std::_Rb_tree<std::string, std::pair<std::string const, std::string>, std::_Select1st<std::pair<std::string const, std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >::_M_get_insert_hint_unique_pos(std::_Rb_tree_const_iterator<std::pair<std::string const, std::string> >, std::string const&) ()
   from /home/lester/Downloads/BioSimSpace.app/lib/python3.7/site-packages/Sire/IO/../../../../../lib/libOpenMM.so
(gdb)
```

**Comment by lohedges** [comment]
It looks like the version of OpenMM that is bundled with Sire is causing the problem...

```python
from simtk.openmm import *
```

...gives:

```bash
[1]    30805 segmentation fault (core dumped)  $HOME/Downloads/BioSimSpace.app/bin/ipython
```

**Comment by lohedges** [comment]
Okay, after more debugging it turns out that the error I was because I had an existing `OPENMM_PLUGIN_DIR` environment variable set, which was pointing to the wrong location. Setting this to the right location fixes the segmentation fault, and the downloaded Linux binary now works on my machine.

To avoid this problem, I had previously updated OpenMMD.py within Sire to set the path to the correctly. I'll look into this to see why it's stopped working.

After merging the latest changes from Sire devel I am now seeing the same test failure as in the Azure build pipeline. I'll work on debugging this.

**Comment by lohedges** [comment]
Right, having run the test manually in a temporary working directory I get the following back trace. Looks like it's definitely a bug introduced via the the SOMD updates.

```bash
Traceback (most recent call last):
  File "/home/lester/sire.app/pkgs/sire-2018.2.0/share/Sire/scripts/somd.py", line 125, in <module>
    OpenMMMD.run(params)
  File "/home/lester/sire.app/lib/python3.5/site-packages/Sire/Tools/__init__.py", line 176, in inner
    retval = func()
  File "/home/lester/sire.app/lib/python3.5/site-packages/Sire/Tools/OpenMMMD.py", line 1409, in run
    moves = setupMoves(system, ranseed, gpu.val)
  File "/home/lester/sire.app/lib/python3.5/site-packages/Sire/Tools/OpenMMMD.py", line 443, in setupMoves
    Integrator_OpenMM.setCombiningRules(combining_rules.val)
AttributeError: 'OpenMMMDIntegrator' object has no attribute 'setCombiningRules'
```

**Comment by lohedges** [comment]
Closing as SOMD breaking changes have been reverted.
